os:
- linux
dist: focal
language: minimal

services:
- docker

# build for all pushes, as well as PRs coming from forks
# this ensures that the pipeline is triggered for internal pushes,
# PRs from forks and pushes to existing PRs from forks
# if: (type == push) OR (type == pull_request AND fork == true)

stages:
- name: publish
  # for security reasons, builds from forks won't be published until merged;
  # also, environment variables defined in repository settings are not
  # available to builds from PRs coming from external repos
  if: fork == false

before_script:
  - |
    export DOCKER_TAG="$(date '+%Y%m%d')"
jobs:
  include:
    - stage: publish
      name: Build and publish
      script:
        - docker build . -t "${DOCKER_REPO_NAME}:latest" -t "${DOCKER_REPO_NAME}:${DOCKER_TAG}"
        - echo "${DOCKER_TOKEN}" | docker login -u "${DOCKER_USER}" --password-stdin
        - docker push "${DOCKER_REPO_NAME}:${DOCKER_TAG}"
        - docker push "${DOCKER_REPO_NAME}:latest"
        - rm ${HOME}/.docker/config.json  # delete token